language: python

python:
  # - "2.6"
  # - "2.7"
  - "3.3"
  - "3.4"
  # - "3.5.0b3"
  # - "3.5-dev"

matrix:
  # allow_failures:
  #   - python: "3.5.0b3"
  #   - python: "3.5-dev"

  fast_finish: true

services:
  - mongodb

install:
  - "pip install -r requirements.txt"

script: py.test -s -v
